#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
  if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
    systemctl enable pysieved.service || true
    systemctl restart pysieved.service || true
  fi
fi

exit 0
